apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginxhello
    build: jenkins-deploy
  name: nginxhello
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginxhello
      name: nginxhello
    spec:
      containers:
        - name: nginxhello
          image: mycluster.icp:8500/default/nginxhello:alpine
          imagePullPolicy: Always
